name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            libopencv-dev \
            libavformat-dev \
            libavcodec-dev \
            libavutil-dev \
            libswscale-dev \
            libmosquitto-dev \
            libcjson-dev \
            libgtest-dev
      # build
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

        # Test
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure